### ISSUE TITLE
reading the do-agent metrics in a grafana dashboard

### ISSUE THREAD

**Issue by linuxexp** [digitalocean/do-agent#226] opened 2020-07-12 16:55 UTC
**_Please only create a Github issue for bugs related to the code itself. If you are 
experiencing an issue with sending metrics, display graphs, errors from the agent,
etc, please contact https://cloudsupport.digitalocean.com/s/ so we can provide support_**

Before opening an issue, make sure there is not a similar issue [already open](https://github.com/digitalocean/do-agent/issues)

## Describe the problem

I understand that do-agent 
- can be made to run on every droplet & by default is not installed.
- I understand that the do-agent exports prom metrics at 127.0.0.1:9100.

I am interested in exporting the metrics to my grafana dashboard. Will that be possible if I import the Prometheus data from `127.0.0.1:9100` after installing the do-agent on a droplet? Is possible to collect similar data from managed database instances?

## System Information
Distribution and version:

### do-agent information:
Paste the entire output

`/opt/digitalocean/bin/do-agent --version`:

_Ubuntu, Debian_

`apt-cache policy do-agent`:

_Fedora, CentOS_

`yum --cacheonly list do-agent`:

**Comment by bsnyder788** [comment] 2020-07-15 20:18
@linuxexp you could definitely use that prometheus endpoint in your own Grafana instance if you like.  You would not be able to collect similar data from a managed database instance though.

**Comment by bsnyder788** [comment] 2020-07-15 20:19
I closed this as it is not a bug related to the actual code.

**Closed by bsnyder788** 2020-07-15 20:18 UTC

**Comment by linuxexp** [comment] 2020-07-21 05:56
Thank you @bsnyder788
