### ISSUE TITLE
tuf error, failed to decode root.json

### ISSUE THREAD

**Issue by ChrisHardie** [digitalocean/do-agent#43] opened 2017-07-24 13:55 UTC
For the last few days I've been seeing this error go by in my logs:

`Unable to update do-agent: Update: Error initializing repository: tuf: failed to decode root.json: expired at 2017-07-22 15:27:54 +0000 UTC`

The do-agent binary was last updated on July 19 and that's about when the issue started. It sounds like tuf is trying to reference a file/resource that is somehow considered expired. 

Looks like others are seeing the same: https://www.digitalocean.com/community/questions/do-agent-unable-to-update

Any advice?

**Comment by laurencei** [comment] 2017-08-05 07:55
I have this exact issue. It is appear on all my droplets (I have 6) - every hour, every droplet since similar time to @ChrisHardie.

I've tried forcing an update (already on `0.5.0`) and uninstall/reinstalling etc - nothing solves it.

**Comment by adiohaion** [comment] 2017-08-13 14:23
I have the same issue on our production server. Also tried to reinstall the agent which didn't help.

**Comment by utlemming** [comment] 2017-08-14 18:45
Fix is inflight. We don't have an update to the agent right now (0.5.0 is the latest), so the message is noise. But I am going to fix it this week :

**Comment by infiniweb** [comment] 2017-08-16 07:23
@utlemming until now I didn't received data in the Graph in DO for my droplet affected by this issue. However since now one or two days I can see data in the Graph section. Was it linked to this issue?

While I still see the tuf error to decode root.json but I get reporting... Every hours I can still see the same error:
`Unable to update do-agent: Update: Error initializing repository: tuf: failed to decode root.json: expired at 2017-07-22 15:27:54 +0000 UTC`

**Comment by utlemming** [comment] 2017-08-16 12:03
Tuf is an update framework which is seperate from the reporting of graphs. If you are not seeing Graphs, please reach out to support; the two issues are seperate. The `root.json` expiration just means that the agent will not update to the next version. Since there is no next version yet, its a cosmetic issue for now.

**Comment by infiniweb** [comment] 2017-08-16 12:19
@utlemming thanks for the clarification.

**Comment by utlemming** [comment] 2017-08-16 21:55
Thank you all for your patience. I've confirmed that the fix is rolled out. Your agents should see the fix shortly.

```
root@agent-tester:/opt/digitalocean/bin# ./do-agent 
2017/08/16 21:54:57 Do-Agent version 0.4.13
2017/08/16 21:54:57 Do-Agent build HEAD.c02cdbe
2017/08/16 21:54:57 Architecture: amd64
2017/08/16 21:54:57 Operating System: linux
2017/08/16 21:54:57 Checking for newer version of do-agent
2017/08/16 21:54:57 Do-Agent version 0.5.0
2017/08/16 21:54:57 Do-Agent build HEAD.a434d05
2017/08/16 21:54:57 Architecture: amd64
2017/08/16 21:54:57 Operating System: linux
2017/08/16 21:54:57 Checking for newer version of do-agent
2017/08/16 21:54:57 No update available
```

**Closed by utlemming** 2017-08-16 21:56 UTC
